---
# defaults/main.yml for mssql_patching

# Target host
mssql_patching_host: ""

# Authentication
mssql_patching_username: ""
mssql_patching_password: ""
mssql_patching_api_key: ""

# Behavior
mssql_patching_validate_certs: true
mssql_patching_state: present
